# Generated by Django 4.0.3 on 2022-03-12 15:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=200)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('count_vote', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='polls.poll')),
            ],
        ),
    ]
