# Generated by Django 4.0.3 on 2022-03-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='polls.poll'),
        ),
    ]
