# Generated by Django 4.0.3 on 2022-03-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_vote_choice_alter_vote_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
