# Generated by Django 4.0.3 on 2022-03-18 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0008_poll_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='polls.poll'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
